import Head from "next/head";
import Link from "next/link";
import { Inter } from "next/font/google";
import { motion } from "framer-motion";
import {
  EmailSVGIcon,
  GithubSVGIcon,
  LinkedinSVGIcon,
} from "~/assets/SvgIcons";
import AboutModal from "~/components/AboutModal";
import { useState } from "react";

const inter = Inter({
  weight: ["100", "200", "400", "700"],
  variable: "--font-inter",
  subsets: ["latin"],
});

export default function Home(): React.ReactElement {
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
  return (
    <>
      <Head>
        <title>Osama Khalil</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`${inter.className}  flex min-h-screen flex-col items-center justify-center bg-stone-950`}
      >
        <AboutModal isModalOpen={isModalOpen} setIsModelOpen={setIsModalOpen} />

        <motion.div
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5 }}
          className="bg-gradient-to-r from-cyan-100 to-slate-200 bg-clip-text text-center text-2xl text-transparent"
        >
          <p className="flex text-center text-sm text-cyan-100 md:justify-start">
            Hi <span className="animate-waving-hand text-center">👋🏻</span>,
          </p>{" "}
          <h1 className="text-4xl font-extrabold sm:text-6xl">
            {" "}
            I'm Osama Khalil
          </h1>
        </motion.div>
        <div className="mt-8 w-5/6 grid-flow-col grid-cols-2 grid-rows-2 gap-8 md:grid md:w-2/3 lg:w-2/4">
          <motion.div
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
            initial={{
              opacity: 0,
              scale: 0.5,
            }}
            animate={{ opacity: 1, scale: 1 }}
            className="mb-4 cursor-pointer rounded-lg bg-stone-800 p-5 text-center shadow-md hover:bg-stone-700 md:mb-0"
          >
            <p className="bg-gradient-to-r from-cyan-100 to-slate-200 bg-clip-text text-2xl text-transparent">
              Projects
            </p>
          </motion.div>
          <motion.div
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
            initial={{ opacity: 0, scale: 0.5 }}
            animate={{ opacity: 1, scale: 1 }}
            className="mb-4 cursor-pointer rounded-lg bg-stone-800 p-5 text-center shadow-md hover:bg-stone-700 md:mb-0"
          >
            <p className="bg-gradient-to-r from-cyan-100 to-slate-200 bg-clip-text text-2xl text-transparent">
              Skills
            </p>
          </motion.div>
          <motion.div
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
            initial={{ opacity: 0, scale: 0.5 }}
            animate={{ opacity: 1, scale: 1 }}
            className="mb-4 cursor-pointer rounded-lg bg-stone-800 p-5 text-center shadow-md hover:bg-stone-700 md:mb-0"
          >
            <p className="bg-gradient-to-r from-cyan-100 to-slate-200 bg-clip-text text-2xl text-transparent">
              Experiences
            </p>
          </motion.div>
          <motion.div
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
            initial={{ opacity: 0, scale: 0.5 }}
            animate={{ opacity: 1, scale: 1 }}
            onClick={() => setIsModalOpen(!isModalOpen)}
            data-modal-target="staticModal"
            data-modal-toggle="staticModal"
            className="mb-4 cursor-pointer rounded-lg bg-stone-800 p-5 text-center shadow-md hover:bg-stone-700 md:mb-0"
          >
            <p className="bg-gradient-to-r from-cyan-100 to-slate-200 bg-clip-text text-2xl text-transparent">
              About
            </p>
          </motion.div>
        </div>
        <motion.div
          className="mt-10 flex flex-col"
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5 }}
        >
          <h1 className="bg-gradient-to-r from-cyan-100 to-slate-200 bg-clip-text text-center text-xl font-bold text-transparent sm:text-2xl">
            Contact + links..
          </h1>
          <motion.div
            className="mt-1 flex flex-row justify-center"
            initial={{ opacity: 0, scale: 0.5 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.5 }}
          >
            <Link
              href={"https://www.linkedin.com/in/osama-khalil98/"}
              target="_blank"
            >
              <LinkedinSVGIcon
                width={24}
                height={24}
                fill={"rgb(207 250 254)"}
              />
            </Link>
            <Link href={"mailto:osadx35@gmail.com"}>
              <EmailSVGIcon width={24} height={24} fill={"rgb(207 250 254)"} />
            </Link>
            <Link href={"https://github.com/osamakhalil98/"} target="_blank">
              <GithubSVGIcon width={24} height={24} fill={"rgb(207 250 254)"} />
            </Link>
          </motion.div>
        </motion.div>
      </main>
    </>
  );
}
